apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumbkv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs # comment this out if running on host path
